apiVersion: v1
kind: Service
metadata:
  name: postgres-production
  labels:
    app: postgres-production
    env: production
    namespace: default
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-production
