apiVersion: v1
kind: Secret
metadata:
  name: care-production
  labels:
    app: care
    env: production
    namespace: default
type: Opaque
stringData:
  DJANGO_SECRET_KEY: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  POSTGRES_PASSWORD: ""
  CELERY_BROKER_URL: "redis://:@redis-cache-production:6379/0"
  REDIS_URL: "redis://:@redis-cache-production:6379/0"
  DJANGO_ADMIN_URL: "adminurl"
  DATABASE_URL: ""
  CURRENT_DOMAIN: "https://care.demo.example.in"
  EMAIL_HOST: ""
  EMAIL_USER: ""
  EMAIL_PASSWORD: ""
  SENTRY_DSN: ""
  SENTRY_ENVIRONMENT: "prod"
  SNS_ACCESS_KEY: ""
  SNS_SECRET_KEY: ""
  FILE_UPLOAD_BUCKET: "care-patient-data-private-bucket"
  FILE_UPLOAD_KEY: ""
  FILE_UPLOAD_SECRET: ""
  AUDIT_LOG_ENABLED: "1"
  GOOGLE_RECAPTCHA_SITE_KEY: ""
  GOOGLE_RECAPTCHA_SECRET_KEY: ""
  VAPID_PUBLIC_KEY: ""
  VAPID_PRIVATE_KEY: ""
  FACILITY_S3_BUCKET: "care-facility-public-bucket"
  FACILITY_S3_KEY: ""
  FACILITY_S3_SECRET: ""
  FACILITY_S3_BUCKET_ENDPOINT: "https://storage.cloud.google.com/care-facility-public-bucket"
  FACILITY_S3_STATIC_PREFIX: "https://storage.cloud.google.com/care-facility-public-bucket"
  # ABDM related configs
  ABDM_URL: "https://dev.abdm.gov.in"
  HEALTH_SERVICE_API_URL: "https://healthidsbx.abdm.gov.in/api"
  X_CM_ID: "sbx"
  ABDM_CLIENT_ID: ""
  ABDM_CLIENT_SECRET: ""
  ENABLE_ABDM: "True"
